version: '3.8'

services:
  backend-api:
    build:
      context: ./backend-api
      target: production
    ports:
      - "8000:8000"
    env_file: .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "80:80"
    env_file: .env
    restart: unless-stopped
